from django.core.management.base import BaseCommand, CommandError
from django.core.management import call_command


class Command(BaseCommand):
    help = "G√©n√®re et compile les fichiers de traduction (.po et .mo) pour en et fr."

    def handle(self, *args, **options):
        try:
            self.stdout.write(self.style.NOTICE("üîç G√©n√©ration des fichiers .po..."))
            call_command("makemessages", "-l", "en")
            call_command("makemessages", "-l", "fr")

            self.stdout.write(self.style.SUCCESS("‚úÖ Fichiers .po g√©n√©r√©s."))

            self.stdout.write(self.style.NOTICE("üõ† Compilation des fichiers .mo..."))
            call_command("compilemessages")

            self.stdout.write(self.style.SUCCESS("‚úÖ Compilation termin√©e avec succ√®s."))

        except Exception as e:
            raise CommandError(f"‚ùå Erreur durant le processus de traduction : {e}")
